const MASTER_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || "AIzaSyCriToueLXKW-tDdUp0L0PKsjZo2ACjHjc";

export const ENV_CONFIG = {
  GOOGLE_MAPS_API_KEY: MASTER_KEY,
  GEMINI_API_KEY: process.env.NEXT_PUBLIC_GEMINI_API_KEY || MASTER_KEY,
};
